import { spawn } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(packageDir, "../..");
const tmpOutDir = path.join(repoRoot, ".omne_data", "tmp", "protocol-package-gen");
const generatedDir = path.join(packageDir, "generated");
const schemaDir = path.join(packageDir, "schema");

async function run(command, args, cwd) {
  await new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd,
      env: process.env,
      stdio: "inherit",
    });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
        return;
      }
      reject(new Error(`${command} exited with code ${code}`));
    });
  });
}

async function runGenerate(kind) {
  const appServerBin = process.env.OMNE_APP_SERVER_BIN;
  if (appServerBin && appServerBin.trim() !== "") {
    await run(appServerBin, [kind, "--out", tmpOutDir], repoRoot);
    return;
  }

  await run(
    "cargo",
    ["run", "-q", "-p", "omne-app-server", "--", kind, "--out", tmpOutDir],
    repoRoot
  );
}

async function walkFiles(root) {
  const out = [];
  async function walk(dir) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(abs);
      } else if (entry.isFile()) {
        out.push(abs);
      }
    }
  }

  try {
    await walk(root);
  } catch (err) {
    if (err && err.code === "ENOENT") return out;
    throw err;
  }

  return out;
}

function toPosixPath(p) {
  return p.split(path.sep).join("/");
}

async function main() {
  await fs.rm(tmpOutDir, { recursive: true, force: true });
  await fs.mkdir(tmpOutDir, { recursive: true });

  await runGenerate("generate-ts");
  await runGenerate("generate-json-schema");

  await fs.rm(generatedDir, { recursive: true, force: true });
  await fs.rm(schemaDir, { recursive: true, force: true });
  await fs.mkdir(generatedDir, { recursive: true });
  await fs.mkdir(schemaDir, { recursive: true });

  const files = await walkFiles(tmpOutDir);
  const dtsFiles = [];

  for (const file of files) {
    const rel = path.relative(tmpOutDir, file);
    if (rel.endsWith(".ts")) {
      const targetRel = rel.slice(0, -3) + ".d.ts";
      const target = path.join(generatedDir, targetRel);
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.copyFile(file, target);
      dtsFiles.push(targetRel);
      continue;
    }

    if (rel.endsWith(".schema.json")) {
      const target = path.join(schemaDir, path.basename(rel));
      await fs.copyFile(file, target);
    }
  }

  dtsFiles.sort((a, b) => a.localeCompare(b));
  const indexLines = [
    "// Generated by packages/omne-app-server-protocol/scripts/sync.mjs",
    "// Source of truth: crates/app-server-protocol + omne-app-server generate-ts",
    "",
  ];

  for (const file of dtsFiles) {
    const noExt = toPosixPath(file).replace(/\.d\.ts$/, "");
    indexLines.push(`export * from \"./generated/${noExt}\";`);
  }

  indexLines.push("");
  await fs.writeFile(path.join(packageDir, "index.d.ts"), indexLines.join("\n"), "utf8");

  const schemaFiles = (await walkFiles(schemaDir))
    .map((abs) => path.basename(abs))
    .filter((name) => name.endsWith(".schema.json"))
    .sort((a, b) => a.localeCompare(b));

  await fs.writeFile(
    path.join(schemaDir, "manifest.json"),
    `${JSON.stringify({ files: schemaFiles }, null, 2)}\n`,
    "utf8"
  );

  process.stdout.write(
    `Synced protocol package: ${dtsFiles.length} types, ${schemaFiles.length} schemas.\n`
  );
}

main().catch((err) => {
  process.stderr.write(`${err.stack || err}\n`);
  process.exit(1);
});
